{% set name = "gdu" %}
{% set version = "5.32.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dundee/gdu/archive/v{{ version }}.tar.gz
  sha256: 2b647c3b222392fcf25583acd2411ec05635055ef7272c7ab4bd2885e53065e0

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - gdu --help

about:
  home: https://github.com/dundee/gdu
  license: MIT
  license_file:
    - LICENSE.md
    - license-files/
  summary: Disk usage analyzer with console interface written in Go
  dev_url: https://github.com/dundee/gdu

extra:
  recipe-maintainers:
    - danielnachun
