schema_version: 1

context:
  version: "5.33.0"

package:
  name: gdu
  version: ${{ version }}

source:
  url: https://github.com/dundee/gdu/archive/v${{ version }}.tar.gz
  sha256: 14419fa66046c9fc2d1a6deae0c784c4ac5561ba97e1bd39d622293530ed2788

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - gdu --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - license-files/
  summary: Disk usage analyzer with console interface written in Go
  homepage: https://github.com/dundee/gdu
  repository: https://github.com/dundee/gdu

extra:
  recipe-maintainers:
    - danielnachun
