schema_version: 1

context:
  version: "5.36.1"

package:
  name: gdu
  version: ${{ version }}

source:
  url: https://github.com/dundee/gdu/archive/v${{ version }}.tar.gz
  sha256: dd31ea9afd848edf734143aabd5fdf66236ce2c866dc09f9dededb61d39fe63c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - gdu --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - license-files/
  summary: Disk usage analyzer with console interface written in Go
  homepage: https://github.com/dundee/gdu
  repository: https://github.com/dundee/gdu

extra:
  recipe-maintainers:
    - danielnachun
