schema_version: 1

context:
  version: "5.36.0"

package:
  name: gdu
  version: ${{ version }}

source:
  url: https://github.com/dundee/gdu/archive/v${{ version }}.tar.gz
  sha256: 40a8635452a333fc74d9f060c9b56b6ebc0c78911f0b6eff498e6303f03505c6

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - gdu --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - license-files/
  summary: Disk usage analyzer with console interface written in Go
  homepage: https://github.com/dundee/gdu
  repository: https://github.com/dundee/gdu

extra:
  recipe-maintainers:
    - danielnachun
