schema_version: 1

context:
  version: "5.34.3"

package:
  name: gdu
  version: ${{ version }}

source:
  url: https://github.com/dundee/gdu/archive/v${{ version }}.tar.gz
  sha256: 06c9a81d1b869dd3620d4892e98b29c33c73ec91c380795c35be4294c71370a8

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - gdu --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - license-files/
  summary: Disk usage analyzer with console interface written in Go
  homepage: https://github.com/dundee/gdu
  repository: https://github.com/dundee/gdu

extra:
  recipe-maintainers:
    - danielnachun
